import type { Metadata } from "next";
import { inter } from "./fonts";
import Header from "@/components/Header";
import PageTransitionProvider from "@/components/PageTransition";
import HomeAppearanceProvider from "@/components/HomeAppearance";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <PageTransitionProvider>
          <HomeAppearanceProvider>
            <Header />
            {children}
          </HomeAppearanceProvider>
        </PageTransitionProvider>
      </body>
    </html>
  );
}
